name: Compile

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build for Linux
        run: deno compile --target x86_64-unknown-linux-gnu -o x86_64-unknown-linux-gnu cli.ts

      - name: Build for Mac One
        run: deno compile --target aarch64-apple-darwin -o aarch64-apple-darwin cli.ts

      - name: Build for Mac Two
        run: deno compile --target x86_64-apple-darwin -o x86_64-apple-darwin cli.ts

      - name: Build for Windows
        run: deno compile --target x86_64-pc-windows-msvc -o x86_64-pc-windows-msvc cli.ts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            x86_64-unknown-linux-gnu
            aarch64-apple-darwin 
            x86_64-apple-darwin
            x86_64-pc-windows-msvc.exe
          token: ${{ secrets.GITHUB_TOKEN }}
